features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://doraemon_0.png'
favicon:
  use_default: 0
  path: 'public://doraemon.png'
  mimetype: image/png
mobile_menu_all_widths: 0
site_branding_bg_color: default
base_primary_color: '#1dbf45'
