_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 26e06ce8-0eda-48b2-be0b-7cb67bc40c5a
name: Veggies
mail: admin@example.com
slogan: 'come, enjoy and eat more leafy green'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
